apiVersion: v1
kind: ConfigMap
metadata:
  name: solidarity-connection-api-config
  namespace: solidarity-connection-namespace
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8080"
  AWS_EC2_METADATA_DISABLED: "true"
  AWS_REGION: "us-east-1"