apiVersion: v1
kind: Secret
metadata:
  name: solidarity-connection-api-secret
  namespace: solidarity-connection-namespace
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "<SOLIDARITY_CONNECTION_DB_CONNECTION_STRING>"
  Mongo__ConnectionString: "<MONGODB_CONNECTION_STRING>"
  Mongo__DatabaseName: "SolidarityConnectionTransparency"
  Mongo__CollectionName: "campaigns"
  Jwt__SecretKey: "<JWT_SECRET_KEY>"