<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SolidarityConnection.Application\SolidarityConnection.Application.csproj" />
    <ProjectReference Include="..\SolidarityConnection.Domain\SolidarityConnection.Domain.csproj" />
    <ProjectReference Include="..\SolidarityConnection.Infrastructure\SolidarityConnection.Infrastructure.csproj" />
  </ItemGroup>
</Project>